#include "Cube.h"

Cube::Cube(double x,double y, double z,double r):x(x),y(y),z(z),r(r){}
void Cube::print(string filename){
    ofstream s(filename.c_str());
    s<<"solid OpenSCAD_Model"<<endl;
    s<<" facet normal -0 0 1"<<endl;
    s<<"  outer loop"<<endl;
    s<<"   vertex "<<x+r/2<<" "<<y+r/2<<" "<<(z+r/2)<<endl;
    s<<"   vertex "<<x+r/2<<" "<<y-r/2<<" "<<(z+r/2)<<endl;
    s<<"   vertex "<<x-r/2<<" "<<y-r/2<<" "<<(z+r/2)<<endl;
    s<<"  endloop"<<endl;
    s<<" endfaect"<<endl;
    s<<" facet normal -0 0 1"<<endl;
    s<<"  outer loop"<<endl;
    s<<"   vertex "<<x+r/2<<" "<<y+r/2<<" "<<(z+r/2)<<endl;
    s<<"   vertex "<<x-r/2<<" "<<y+r/2<<" "<<(z+r/2)<<endl;
    s<<"   vertex "<<x-r/2<<" "<<y-r/2<<" "<<(z+r/2)<<endl;
    s<<"  endloop"<<endl;
    s<<" endfaect"<<endl;
    s<<" facet normal -0 0 -1"<<endl;
    s<<"  outer loop"<<endl;
    s<<"   vertex "<<x+r/2<<" "<<y+r/2<<" "<<(z-r/2)<<endl;
    s<<"   vertex "<<x+r/2<<" "<<y-r/2<<" "<<(z-r/2)<<endl;
    s<<"   vertex "<<x-r/2<<" "<<y-r/2<<" "<<(z-r/2)<<endl;
    s<<"  endloop"<<endl;
    s<<" endfaect"<<endl;
    s<<" facet normal -0 0 -1"<<endl;
    s<<"  outer loop"<<endl;
    s<<"   vertex "<<x+r/2<<" "<<y+r/2<<" "<<(z-r/2)<<endl;
    s<<"   vertex "<<x-r/2<<" "<<y+r/2<<" "<<(z-r/2)<<endl;
    s<<"   vertex "<<x-r/2<<" "<<y-r/2<<" "<<(z-r/2)<<endl;
    s<<"  endloop"<<endl;
    s<<" endfaect"<<endl;
    s<<" facet normal -0 1 0"<<endl;
    s<<"  outer loop"<<endl;
    s<<"   vertex "<<x+r/2<<" "<<y+r/2<<" "<<(z+r/2)<<endl;
    s<<"   vertex "<<x-r/2<<" "<<y+r/2<<" "<<(z-r/2)<<endl;
    s<<"   vertex "<<x-r/2<<" "<<y+r/2<<" "<<(z+r/2)<<endl;
    s<<"  endloop"<<endl;
    s<<" endfaect"<<endl;
    s<<" facet normal -0 1 0"<<endl;
    s<<"  outer loop"<<endl;
    s<<"   vertex "<<x+r/2<<" "<<y+r/2<<" "<<(z+r/2)<<endl;
    s<<"   vertex "<<x-r/2<<" "<<y+r/2<<" "<<(z-r/2)<<endl;
    s<<"   vertex "<<x+r/2<<" "<<y+r/2<<" "<<(z-r/2)<<endl;
    s<<"  endloop"<<endl;
    s<<" endfaect"<<endl;
    s<<" facet normal -0 -1 0"<<endl;
    s<<"  outer loop"<<endl;
    s<<"   vertex "<<x+r/2<<" "<<y-r/2<<" "<<(z+r/2)<<endl;
    s<<"   vertex "<<x-r/2<<" "<<y-r/2<<" "<<(z-r/2)<<endl;
    s<<"   vertex "<<x-r/2<<" "<<y-r/2<<" "<<(z+r/2)<<endl;
    s<<"  endloop"<<endl;
    s<<" endfaect"<<endl;
    s<<" facet normal -0 -1 0"<<endl;
    s<<"  outer loop"<<endl;
    s<<"   vertex "<<x+r/2<<" "<<y-r/2<<" "<<(z+r/2)<<endl;
    s<<"   vertex "<<x-r/2<<" "<<y-r/2<<" "<<(z-r/2)<<endl;
    s<<"   vertex "<<x+r/2<<" "<<y-r/2<<" "<<(z-r/2)<<endl;
    s<<"  endloop"<<endl;
    s<<" endfaect"<<endl;
    s<<" facet normal 1 0 0"<<endl;
    s<<"  outer loop"<<endl;
    s<<"   vertex "<<x+r/2<<" "<<y+r/2<<" "<<(z+r/2)<<endl;
    s<<"   vertex "<<x+r/2<<" "<<y-r/2<<" "<<(z-r/2)<<endl;
    s<<"   vertex "<<x+r/2<<" "<<y+r/2<<" "<<(z-r/2)<<endl;
    s<<"  endloop"<<endl;
    s<<" endfaect"<<endl;
    s<<" facet normal 1 0 0"<<endl;
    s<<"  outer loop"<<endl;
    s<<"   vertex "<<x+r/2<<" "<<y+r/2<<" "<<(z+r/2)<<endl;
    s<<"   vertex "<<x+r/2<<" "<<y-r/2<<" "<<(z-r/2)<<endl;
    s<<"   vertex "<<x+r/2<<" "<<y-r/2<<" "<<(z+r/2)<<endl;
    s<<"  endloop"<<endl;
    s<<" endfaect"<<endl;
    s<<" facet normal -1 0 0"<<endl;
    s<<"  outer loop"<<endl;
    s<<"   vertex "<<x-r/2<<" "<<y+r/2<<" "<<(z+r/2)<<endl;
    s<<"   vertex "<<x-r/2<<" "<<y-r/2<<" "<<(z-r/2)<<endl;
    s<<"   vertex "<<x-r/2<<" "<<y+r/2<<" "<<(z-r/2)<<endl;
    s<<"  endloop"<<endl;
    s<<" endfaect"<<endl;
    s<<" facet normal -1 0 0"<<endl;
    s<<"  outer loop"<<endl;
    s<<"   vertex "<<x-r/2<<" "<<y+r/2<<" "<<(z+r/2)<<endl;
    s<<"   vertex "<<x-r/2<<" "<<y-r/2<<" "<<(z-r/2)<<endl;
    s<<"   vertex "<<x-r/2<<" "<<y-r/2<<" "<<(z+r/2)<<endl;
    s<<"  endloop"<<endl;
    s<<" endfaect"<<endl;
    s<<"endsolid OpenSCAD_Model";                             
}